### ISSUE TITLE
Updated Sample

### ISSUE THREAD

**Issue by SkiGeek82** [StefH/angular2-odata#10]
Could you please provide an updated sample that uses @NgModule?  It would be great, If it was broken out into sections for each file.  IE:  app.module.ts, app.component.ts, notify.component.ts

**Comment by StefH** [comment]
Hi @SkiGeek82, I don't understand exactly what you want. This library is only for OData support.

If you want to see a working example for this library in relation to Angular2, see this: https://github.com/StefH/angular2-webpack-starter/tree/_stef_dev/src/app/car

**Comment by SkiGeek82** [comment]
Thank, the referenced example makes more sense
